### PR TITLE
Adding Session 1

### PR DESCRIPTION
**Pull request by christopher-hakkaart**
Draft PR for visibility - rewriting session 1 for the Hello Nextflow workshop.

### CODE REVIEW

**Comment by christopher-hakkaart** [comment]
Hi @georgiesamaha and @fredjaya 

I spent some time fleshing out Session 1.

It's still a little skinny on detail and I still need to add diagrams and learning objectives, but this is the general direction I was thinking.

Some points:
- I've updated the mkdocs.yml to help organise the content and create drop-downs in the nav bar
- The content I've added is very basic, I'm toying with the idea of adding another short sub-section about output variables, as I don't touch them and this will take some pressure off on day 2 (@fredjaya lmk what you think)
- My formatting is wild, ignore that for now, I'll fix it shortly
- Some of the sections could be moved around, I tried not to overthink it and stayed with a previous narrative (start with hard code before moving to variables and parameters) but your input would be valued

If you're happy (or close enough to happy) can we merge this in so we can set the mkdocs.yml in place?

**Comment by fredjaya** [comment]
Will have a look in more detail soon, but agree with merging this first before day 2 changes to get the mkdocs.yml in place

**Comment by fredjaya** [comment]
Looks good to me, a lot that can be linked back to in day 2.

The explanation on Channels will be particularly helpful. 

A bit on output variables would be great!

**Comment by christopher-hakkaart** [comment]
Confirming I'll add an expanded description about Channels, and another section about output variables.

**Comment by christopher-hakkaart** [comment]
I'm my own worst enemy here and decided to move some content around.

Inputs and outputs now come before parameters to give the transition between hard coded inputs and outputs into variable (and now dynamically named) outputs an improved flow (IMO).

I'm considering adding in a parameter for outdir as it's very visible. I took this out as it was repetitive, but now I'm wondering if it should be back in there. LMK

**Pull request merged**
